name: Ubuntu CI

on:
  pull_request:
  push:
    branches:
      - 'ign-plugin[0-9]'
      - 'gz-plugin[0-9]'
      - 'main'

jobs:
  bionic-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Bionic CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile and test
        id: ci
        uses: ignition-tooling/action-ignition-ci@bionic
        with:
          codecov-enabled: true
          doxygen-enabled: true
  focal-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Focal CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile and test
        id: ci
        uses: ignition-tooling/action-ignition-ci@focal
  jammy-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Jammy CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile and test
        id: ci
        uses: ignition-tooling/action-ignition-ci@jammy

